version: "3.8"

services:
  dockerize_xapp_mysql_service:
    build:
      context: ./infra/database/mysql
      dockerfile: Dockerfile
    image: dockerize_xapp_mysql_image:v1
    container_name: dockerize_xapp_mysql_container
    env_file:
      - ./infra/database/mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 10.10.0.100 # IP for MySQL

  dockerize_xapp_php_service:
    build:
      context: ./infra/web/php
      dockerfile: Dockerfile
    image: dockerize_xapp_php_image:v1
    container_name: dockerize_xapp_php_container
    working_dir: /var/www/html
    env_file:
      - ./infra/web/php/.env
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./infra/web/php:/var/www/html
      - ./infra/web/php/vendor:/var/www/html/vendor
    depends_on:
      - dockerize_xapp_mysql_service
    networks:
      app_network:
        ipv4_address: 10.10.0.101 # IP for PHP

  dockerize_xapp_nginx_service:
    build:
      context: ./infra/web/nginx
      dockerfile: Dockerfile
    image: dockerize_xapp_nginx_image:v1
    container_name: dockerize_xapp_nginx_container
    working_dir: /var/www/html
    env_file:
      - ./infra/web/nginx/.env
    restart: always
    ports:
      - "80:80"
    depends_on:
      - dockerize_xapp_php_service
    networks:
      app_network:
        ipv4_address: 10.10.0.102 # IP for Nginx

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.0.0/24" # subnet for the network
          gateway: "10.10.0.1" # gateway for the subnet
    external: false
