apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerize-xapp-mysql-servic-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/mysql
