---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dockerize-xapp-mysql-service-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dockerize-xapp-mysql-service
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy: # safe min/max limits on VPA suggestions
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: "100m"
          memory: "256Mi"
        maxAllowed:
          cpu: "500m"
          memory: "1Gi"
