---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerize-xapp-nginx-service
  labels:
    app: dockerize-xapp-nginx-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerize-xapp-nginx-service
  template:
    metadata:
      labels:
        app: dockerize-xapp-nginx-service
    spec:
      containers:
        - name: dockerize-xapp-nginx-service
          image: soulaimaneyhcodpartner/dockerize_xapp_nginx_image:v1
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 80
