---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerize-xapp-php-service
  labels:
    app: dockerize-xapp-php-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerize-xapp-php-service
  template:
    metadata:
      labels:
        app: dockerize-xapp-php-service
    spec:
      containers:
        - name: dockerize-xapp-php-service
          image: soulaimaneyhcodpartner/dockerize_xapp_php_image:v1
          ports:
            - containerPort: 9000
