---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerize-xapp-nginx-service
  labels:
    app: dockerize-xapp-nginx-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerize-xapp-nginx-service
  template:
    metadata:
      labels:
        app: dockerize-xapp-nginx-service
    spec:
      containers:
        - name: dockerize-xapp-nginx-service
          image: soulaimaneyhcodpartner/dockerize_xapp_nginx_image:v1
          resources:
            requests:
              cpu: "100m" # min CPU (100 millicores = 0.1 CPU core)
              memory: "128Mi" # 128 Mebibytes
            limits:
              cpu: "500m" # max CPU (500 millicores = 0.5 CPU core)
              memory: "256Mi" # 128 Mebibytes
          ports:
            - containerPort: 80
