---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dockerize-xapp-nginx-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dockerize-xapp-nginx-service
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20 # wait 20s before scaling up
    scaleDown:
      stabilizationWindowSeconds: 20 # wait 20s before scaling down
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
