---
apiVersion: v1
kind: Service
metadata:
  name: dockerize-xapp-mysql-service
spec:
  selector:
    app: dockerize-xapp-mysql-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
