---
apiVersion: v1
kind: Service
metadata:
  name: dockerize-xapp-redis-service
spec:
  selector:
    app: dockerize-xapp-redis-service
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
