---
apiVersion: v1
kind: Service
metadata:
  name: dockerize-xapp-php-service
spec:
  selector:
    app: dockerize-xapp-php-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
