apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerize-php
  labels:
    app: dockerize-php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockerize-php
  template:
    metadata:
      labels:
        app: dockerize-php
    spec:
      containers:
        - name: php
          image: soulaimaneyhcodpartner/dockerize_php_xapp:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dockerize-php-service
spec:
  selector:
    app: dockerize-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
