name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: |
          cd infra/web/php
          composer validate --strict

      - name: Install dependencies
        run: |
          cd infra/web/php
          composer install --prefer-dist --no-interaction --no-progress

  cd:
    runs-on: ubuntu-latest
    needs: ci
    timeout-minutes: 10

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        timeout-minutes: 5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.XTOKEN }}
        timeout-minutes: 5

      - name: Build Infra/PHP Docker image
        run: |
          cd infra/web/php
          docker build -t dockerize_php:v1 .
        timeout-minutes: 5

      - name: Push Infra/PHP Docker image to Docker Hub
        run: |
          docker tag dockerize_php:v1 ${{ secrets.DOCKER_USERNAME }}/dockerize_php:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerize_php:v1
        timeout-minutes: 5

      - name: Push Infra/PHP Docker image to GHCR
        run: |
          docker tag dockerize_php:v1 ghcr.io/${{ github.repository_owner }}/dockerize_php:v1
          docker push ghcr.io/${{ github.repository_owner }}/dockerize_php:v1
        timeout-minutes: 5

      - name: Build Infra/Nginx Docker image
        run: |
          cd infra/web/nginx
          docker build -t dockerize_nginx:v1 .
        timeout-minutes: 5

      - name: Push Infra/Nginx Docker image to Docker Hub
        run: |
          docker tag dockerize_nginx:v1 ${{ secrets.DOCKER_USERNAME }}/dockerize_nginx:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerize_nginx:v1
        timeout-minutes: 5

      - name: Push Infra/Nginx Docker image to GHCR
        run: |
          docker tag dockerize_nginx:v1 ghcr.io/${{ github.repository_owner }}/dockerize_nginx:v1
          docker push ghcr.io/${{ github.repository_owner }}/dockerize_nginx:v1
        timeout-minutes: 5

      - name: Build Infra/mysql Docker image
        run: |
          cd infra/database/mysql
          docker build -t dockerize_mysql:v1 .
        timeout-minutes: 5

      - name: Push Infra/mysql Docker image to Docker Hub
        run: |
          docker tag dockerize_mysql:v1 ${{ secrets.DOCKER_USERNAME }}/dockerize_mysql:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerize_mysql:v1
        timeout-minutes: 5

      - name: Push Infra/mysql Docker image to GHCR
        run: |
          docker tag dockerize_mysql:v1 ghcr.io/${{ github.repository_owner }}/dockerize_mysql:v1
          docker push ghcr.io/${{ github.repository_owner }}/dockerize_mysql:v1
        timeout-minutes: 5
